# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - 2023-mayankgg-angular

on:
  push:
    branches:
      - main
    paths:
      - 2023-AngularWebApp/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '18.x'

      - name: npm install
        run: |
          npm install
        working-directory: 2023-AngularWebApp

      - name: Replace secret
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '{'
          tokenSuffix: '}'
          files: '2023-AngularWebApp/src/environments/environment.prod.ts'
        env:
          SECRET_API_KEY: ${{ secrets.API_KEY}}
          SECRET_API_URL: ${{ secrets.API_URL}}
          SECRET_CLIENT_ID: ${{ secrets.CLIENT_ID}}
          SECRET_AUDIENCE: ${{ secrets.AUDIENCE}}

      - name: Build
        run: npm run build:production
        working-directory: 2023-AngularWebApp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: dist/2023-web-app/
        working-directory: 2023-AngularWebApp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: '2023-mayankgg-angular'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C05B9429CB2F4ACFB9D3C6BF048AA96B }}
          package: .
